export const styles = {
  container: {
    width: '100%',
    height: '100%',
    minWidth: 280,
    minHeight: 300,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column' as const,
    background: 'linear-gradient(135deg, #FFF9F0 0%, #FFF5F5 50%, #F0F9FF 100%)',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  header: {
    padding: '16px',
    background: 'rgba(255, 255, 255, 0.85)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderBottom: '1px solid rgba(255, 255, 255, 0.5)',
    boxShadow: '0 2px 12px rgba(0, 0, 0, 0.06)',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
  },
  logoIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    background: 'linear-gradient(135deg, #FF6B9D 0%, #FFB84D 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 12px rgba(255, 107, 157, 0.3)',
  },
  logoText: {
    fontSize: '18px',
    fontWeight: 700,
    color: '#333',
    letterSpacing: '-0.5px',
  },
  searchRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '12px',
  },
  searchInput: {
    flex: 1,
    height: '40px',
    padding: '0 14px',
    fontSize: '14px',
    borderRadius: '20px',
    border: '2px solid rgba(255, 255, 255, 0.8)',
    background: 'rgba(255, 255, 255, 0.9)',
    outline: 'none',
    color: '#333',
    boxShadow: 'inset 0 1px 3px rgba(0, 0, 0, 0.05)',
  },
  searchButton: {
    height: '40px',
    padding: '0 18px',
    fontSize: '14px',
    fontWeight: 600,
    color: '#fff',
    background: 'linear-gradient(135deg, #FF6B9D 0%, #FFB84D 100%)',
    border: 'none',
    borderRadius: '20px',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(255, 107, 157, 0.35)',
    transition: 'all 0.2s ease',
  },
  platformRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
  },
  platformButton: (selected: boolean, color: string) => ({
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    padding: '6px 12px',
    fontSize: '12px',
    fontWeight: 600,
    borderRadius: '16px',
    border: selected ? '2px solid currentColor' : '2px solid rgba(255, 255, 255, 0.6)',
    background: selected ? color : 'rgba(255, 255, 255, 0.7)',
    color: selected ? '#333' : '#888',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: selected ? '0 2px 8px rgba(0, 0, 0, 0.1)' : 'none',
  }),
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '12px 16px',
  },
  resultCard: (bgColor: string) => ({
    padding: '12px 14px',
    marginBottom: '10px',
    borderRadius: '14px',
    background: bgColor,
    border: '1px solid rgba(255, 255, 255, 0.8)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.04)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  }),
  resultTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#1a1a1a',
    lineHeight: 1.4,
    marginBottom: '4px',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
  },
  resultDesc: {
    fontSize: '11px',
    color: '#666',
    lineHeight: 1.5,
    marginBottom: '6px',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
  },
  resultMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '10px',
    color: '#999',
  },
  badge: (bgColor: string) => ({
    display: 'inline-block',
    padding: '2px 8px',
    fontSize: '10px',
    fontWeight: 700,
    color: '#fff',
    borderRadius: '10px',
    background: bgColor,
  }),
  emptyState: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: '80px',
  },
  emptyIcon: {
    width: '64px',
    height: '64px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #FFB3B3 0%, #FFC2E2 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
    boxShadow: '0 8px 24px rgba(255, 107, 157, 0.25)',
  },
  loadingCard: {
    padding: '12px 14px',
    marginBottom: '10px',
    borderRadius: '14px',
    background: 'rgba(255, 255, 255, 0.7)',
    border: '1px solid rgba(255, 255, 255, 0.8)',
  },
  errorBox: {
    padding: '12px 14px',
    marginBottom: '12px',
    borderRadius: '12px',
    background: '#FFF0F0',
    border: '1px solid #FFCCCC',
  },
  resultCount: {
    fontSize: '12px',
    color: '#888',
    marginBottom: '10px',
    paddingLeft: '2px',
  },
};
